name: Notify OSSMC Frontend Sync

on:
  push:
    branches: [v2.27, v2.22, v2.17, v2.11, v2.4]
    paths:
    - 'frontend/src/**'
    - 'frontend/public/locales/**'
    - 'frontend/cypress/integration/**'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch to OSSMC
      uses: actions/github-script@b7fb2001b410c9390cbe9e2c7d5cab7eefb7b29c # v7.0.1
      with:
        github-token: ${{ secrets.KIALI_BOT_TOKEN }}
        script: |
          await github.rest.repos.createDispatchEvent({
            owner: 'ferhoyos',
            repo: 'openshift-servicemesh-plugin',
            event_type: 'kiali-frontend-updated',
            client_payload: {
              branch: '${{ github.ref_name }}'
            }
          });
